# Site settings
title: "agin719's blog"
email: agin719@126.com
description: > # this means to ignore newlines until "baseurl:"
  contact me by e-mail agin719@126.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://agin719.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
